spring:
  jpa:
    # 개발 시에는 테이블 자동 변경/생성을 허용
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Docker Compose로 띄울 컨테이너 이름(dev-db)으로 접속
    url: jdbc:mysql://dev-db:3306/cams?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${DEV_DB_PASSWORD} # 개발용 DB 비밀번호