spring:
  jpa:
    # 개발 시에는 테이블 자동 변경/생성을 허용
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Docker Compose로 띄울 컨테이너 이름(dev-db)으로 접속
    # env 파일에서 덮어쓰기 됨!
    url: jdbc:mysql://cams-db-dev:3306/cams?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DEV_DB_PASSWORD} # 개발용 DB 비밀번호