spring:
  jpa:
    # ⚠️ 운영에서는 절대 create, update를 사용하지 않습니다.
    #    JPA 엔티티와 DB 스키마가 일치하는지 검증만 하도록 설정합니다.
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Docker Compose로 띄울 컨테이너 이름(prod-db)으로 접속
    url: jdbc:mysql://prod-db:3306/cams?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${PROD_DB_PASSWORD} # 운영용 DB 비밀번호