name: BE-PROD :: Build and Deploy to Prod Server
on:
  push:
    branches: [ main ] # main 브랜치에 푸시될 때 실행
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ... (위 dev와 동일, tags와 script 부분만 다름) ...
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ehgus8910/cams-backend:latest-prod # prod용 태그
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/app
            docker-compose -f docker-compose.yml pull cams-backend-prod # prod용 파일과 서비스 이름
            docker-compose -f docker-compose.yml up -d --no-deps cams-backend-prod