name: "BE-DEV :: Build and Deploy to Dev Server"

on:
  push:
    # dev 브랜치에 푸시될 때 실행
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ehgus8910/cams-backend:latest-dev

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            cd /home/cpu/app
            
            # 사용하지 않는 옛날 이미지가 서버에 쌓이는 것을 방지하기 위해 이미지 정리 명령어를 추가하면 좋습니다.
            docker image prune -f
            
            # up 명령어에 --pull always 옵션을 추가하여 항상 최신 이미지를 받아오도록 강제합니다.
            # --force-recreate 옵션과 함께 사용하면 완벽하게 새로운 컨테이너로 교체됩니다.
            docker-compose -f docker-compose.dev.yml up -d --force-recreate --pull always cams-backend-dev
            


